config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  #only keyword removes the other routes from the resources
  
  #this allows us to expose only the routes that we want for the program
  #resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  #this exposes all routes, including REST-ful routes
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: true, 
                    length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, 
                          length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of  :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password                  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
     flash[:alert] = "You must be logged in to perform that action."
     redirect_to login_path
   end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    # byebug is used to stop execution and get a debugger console
    # byebug
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    #redirect_to article_path(@article)

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  #anything below private can only be seen by this file
  #it doesn't require an end
  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]


  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category successfully created."
      redirect_to @category
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name successfully updated."
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha Blog, #{@user.username}! Signup successful"
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted."
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container-fluid">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card articles-card-div">
          <h5 class="card-header article-header"><%= link_to article.title, article_path(article), class:"article-show-link" %></h5>
          <div class="card-body">
            <h5 class="card-title text-truncate"><%= article.description %></h5>
            <p class="card-text">
              <% if article.user %>
                <%= link_to article.user.username, user_path(article.user), class:"user-show-link" %>, created <%= time_ago_in_words(article.created_at) %> ago/edited <%= time_ago_in_words(article.updated_at) %> ago
              <% end %>
            </p>
            <%= link_to 'View', article_path(article), class: "btn btn-primary action-button"%>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary action-button edit-button" %>
              <%= button_to 'Delete', article_path(article.id), method: :delete, data: { turbo_confirm: "Are you sure?" }, class:"btn btn-primary action-button delete-button", form: {style:"display:inline-block;"}%>
            <% end %>
          </div>
          <% if article.categories.any? %>
            <div class="card-footer text-muted", style="background-color:#e4d7db; border-top-color:#c88995;">
              <div class="mt-1 mb-1"><%= render article.categories %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_article_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10"> <%= render 'shared/errors', obj: @article %> </div>
    <div class="col-10 form-style">
      <%= form_with(model: @article, local: true) do |f| %>
        <div class="form-group row mt-3">
          <%= f.label :title, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.text_field :title, class:"form-control", placeholder:"Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3 mb-3">
          <%= f.label :description, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.text_area :description, rows:10, class:"form-control", placeholder:"Description of article" %>
          </div>
        </div>

        <div class="form-group row mt-3 mb-3">
          <%= f.label :category, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, 
                                    { prompt: "Select your categories (optional)" }, 
                                    { multiple: true, size: 4, class: "form-select" }) %>
          </div>
        </div>

        <div class="form-group justify-content-center row mb-3">
          <%= f.submit class: "btn btn-primary action-button col-auto" %>
        </div>
      <% end %>
    </div>

    <%= link_to 'Return to articles listing', articles_path, class:"dark-pink-text return-link" %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, style: "display: block"" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Edit existing article</h1>
<%= render 'article_form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Articles</h1>

<%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
<%= render 'article' %>
<%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center mt-4) %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Create a new article</h1>
<%= render 'article_form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-2" style="color:#c88995;"><%= @article.title %></h1>

<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-1">
      <div class="card articles-card-div">
        <div class="card-body">
          <% if @article.categories.any? %>
            <div class=mb-2><%= render @article.categories %></div>
          <% end %>
          <h5 class="card-title"><%= simple_format(@article.description) %></h5>
          <p class="card-text"><%= @article.user.username %>, created <%= time_ago_in_words(@article.created_at) %> ago/edited <%= time_ago_in_words(@article.updated_at) %> ago</p>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary action-button edit-button" %>
            <%= button_to 'Delete', article_path(@article.id), method: :delete, data: { turbo_confirm: "Are you sure?" }, class:"btn btn-primary action-button delete-button", form: {style:"display:inline-block;"}%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge rounded-pill text-bg-primary", style= "font-size:0.9em; margin-right: 2px;">
  <%= link_to category.name, category_path(category), class: "badge-link" %>
</span>

app/views/categories/_form.html.erb
<div class="col-10"> 
  <%= render 'shared/errors', obj: @category %>
</div>
<div class="col-10 form-style">
  <%= form_with(model: @category, local: true) do |f| %>
    <div class="form-group row mt-3">
      <%= f.label :name, class: "col-2 col-form-label dark-pink-text" %><br/>
      <div class="col-10">
        <%= f.text_field :name, class:"form-control", placeholder:"Enter category name" %>
      </div>
    </div>

    <div class="form-group justify-content-center row mb-3">
      <%= f.submit class: "btn btn-primary action-button col-auto mt-1" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Edit existing category</h1>

<div class="container">
  <div class="row justify-content-center">
    <%= render 'form' %>
    <%= link_to 'Return to category', categories_path(@category), class:"dark-pink-text return-link" %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Categories</h1>

<%= will_paginate @categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>

<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card articles-card-div">
        <div class="card-body">
          <h3 class="card-title text-truncate"><%= link_to category.name, category_path(category) %></h3>
          <h5 class="card-text">
            <%= pluralize(category.articles.count, "article") %>
          </h5>
          <div class="card-footer", style="background-color:#e4d7db; border-top-color:#c88995;">
            <div class="mt-1 mb-1">
            Created <%= time_ago_in_words(category.created_at) %> ago/edited <%= time_ago_in_words(category.updated_at) %> ago
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= will_paginate @categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center mt-4) %>

app/views/categories/new.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Create a new category</h1>

<div class="container">
  <div class="row justify-content-center">
    <%= render 'form' %>

    <%= link_to 'Return to categories listing', categories_path, class:"dark-pink-text return-link" %>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">
  Category: <%= @category.name %>
</h1>

<hr/>

<div class="text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-sm btn-primary action-button edit-button" %>
  <% end %>
</div>
<h3 class="text-center mt-4" style="color:#c88995;">Articles</h3>
<%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
<%= render 'articles/article' %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom" style="background-color:#c88995;">
    <div class="container" style="margin:auto; width: 50%;">
      <p class="text-muted" id="footer-text">Copyright <i class="fa fa-copyright"></i> <%= link_to "Armadillo_Codes", "https://www.armadillo-codes.com", id: "footer-text" %></p>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name,msg| %>
    <% if name == 'notice' %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% else %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>


  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <i class="fa fa-heart" style="font-size: 2em; padding-right: 2px; color: white;"></i>
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon navbar-dark"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu dropdown-style">
            <% if logged_in? %>
              <li>
                <%= link_to "Create new article", new_article_path, class: "dropdown-item nav-link nav-link-drop" %>
              </li>
            <% end %>
            <li>
              <%= link_to "View articles", articles_path, class: "dropdown-item nav-link nav-link-drop" %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <% if logged_in? && current_user.admin? %>
              <li>
                <%= link_to "Create new category", new_category_path, class: "dropdown-item nav-link nav-link-drop" %>
              </li>
            <% end %>
            <li>
              <%= link_to "View categories", categories_path, class: "dropdown-item nav-link nav-link-drop" %>
            </li>
          </ul>
        </li>
        
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
          </a>
          <ul class="dropdown-menu dropdown-style">
            <li>
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item nav-link nav-link-drop" %>
            </li>
            <li>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item nav-link nav-link-drop" %>
            </li>
          </ul>
        </li>
          <li class="nav-item">
            <%= button_to 'Log out', logout_path, class: "nav-button nav-link", method: :delete, form: { class: "text-center" } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container" id="home-container">
  <div class="p-5 mb-4 bg-light rounded-3" id="jumbotron">
    <div class="container-fluid py-5" style="margin: auto; width: 50%;">
      <h1 class="display-5 fw-bold">about me</h1>
      <p class="col-md-8 fs-4">my name is fen and i'm a new developer! i love learning and cats :)</p>
      <button class="btn btn-primary btn-lg" id="home-button" type="button">
      <%= link_to 'Read more', articles_path, id:"home-button" %>
      </button>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="p-5 mb-4 bg-light rounded-3" id="jumbotron">
    <div class="container-fluid py-5" style="margin: auto; width: 50%;">
      <h1 class="display-5 fw-bold">Hello, World!</h1>
      <p class="col-md-8 fs-4">Welcome to the alpha blog! Sign up and tell me about development :)</p>
      <button class="btn btn-primary btn-lg" id="home-button" type="button">
        <%= link_to 'Sign up!', signup_path, id:"home-button" %>
      </button>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <hr>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10"> <%= render 'shared/errors', obj: @user %> </div>
    <div class="col-10 form-style">
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group row mt-3">
          <%= f.label :username, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.text_field :username, class:"form-control", placeholder:"Enter a username" %>
          </div>
        </div>

        <div class="form-group row mt-3 mb-3">
          <%= f.label :email, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.email_field :email, class:"form-control", placeholder:"Enter your email address" %>
          </div>
        </div>

        <div class="form-group row mt-3 mb-3">
          <%= f.label :password, class: "col-2 col-form-label dark-pink-text" %><br/>
          <div class="col-10">
            <%= f.password_field :password, class:"form-control", placeholder:"Enter a unique password" %>
          </div>
        </div>

        <div class="form-group justify-content-center row mb-3">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary action-button col-auto") %>
          <% if !@user.new_record? %>
            <%#= f.button "Delete account", type: "submit", name: "commit", value: "delete_account", class: "btn btn-primary action-button delete-button col-auto", style:"margin-left: 5px;" %>
            <%=
              button_tag(
                "Delete account", 
                form: "optionalone", 
                type: "submit", 
                data: { turbo_confirm: "Are you sure?" }, 
                name: "commit", value: "delete_account", 
                class: "btn btn-primary action-button delete-button col-auto", 
                style:"margin-left: 5px;"
              ) 
            %>
          <% end %>
        </div>
      <% end %>
      <% if !@user.new_record? %>
        <%= form_with(model: @user, method: :delete, id: "optionalone") {} %>
      <% end %>
    </div>

    <%= link_to 'Return to articles listing', articles_path, class:"dark-pink-text return-link" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Edit Your Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Bloggers</h1>

<%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
<div class="container-fluid">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card articles-card-div">
          <h5 class="card-header article-header"><%= link_to user.username, user_path(user), class:"article-show-link" %></h5>
          <div class="card-body">
            <h5 class="card-title"><%= pluralize(user.articles.count, "article") %></h5>
            <p class="card-text">Joined <%= time_ago_in_words(user.created_at)%> ago</p>
            <%= link_to 'View Profile', user, class: "btn btn-primary action-button"%>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-primary action-button edit-button" %>
              <% end %>
              <% if current_user.admin? %>
              <%= button_to 'Delete profile', user_path(user.id), method: :delete, data: { turbo_confirm: "Are you sure?" }, class:"btn btn-primary action-button delete-button", form: {style:"display:inline-block;"}%>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center mt-4) %>

app/views/users/new.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">Sign Up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4" style="color:#c88995;">
  <%= @user.username %>'s profile
</h1>
<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-sm btn-primary action-button edit-button" %>
  <% end %>
</div>
<h3 class="text-center mt-4" style="color:#c88995;">Articles</h3>
<%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
<%= render 'articles/article' %>